language: python
sudo: required
dist: xenial
python: '3.7'
env:
  global:
  - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
  - LAMBDA_FUNCTION_NAME=flask-api-proxy-example
  - LAMBDA_RUNTIME=python3.7
  - LAMBDA_ROLE=arn:aws:iam::611162374248:role/service-role/datalync-lambda-service
  - LAMBDA_FUNCTION_CODE_ZIP=dist/flask-api-proxy-example.zip
  - LAMBDA_FUNCTION_HANDLER=lambda_function.lambda_handler
  - AWS_DEFAULT_REGION=us-east-1
  - secure: F5XPwbRp3cRTMB2DJYgsKwQVV4DPhuHJfZeXnKilwAN7P9HKqNFKfTvHcSG/71cpOh6rOiJsdUmIACVyCB2ACYmmzOcfMrqaOGZozwgQX5mPZEaWnUujcn8JunNhzTZywNYqYd1E0bgDQt9w03A53RIZgLUjpezepkJrHs7ug/3QHOOfoGpiYdjAp0tHJ76z0/qVvOqYCaOI0BEqq+9tkYkCpTyEdzkkzZ+uhxcjY/RE4Aju5u0qBqyh4FnzIuKnrm22Tdqf3MjWQPqwTwhW5mQVgkQsjK9NbDxTSBezb3syu3BUFVevtriuVI5wJXTqq3hg4/+tWUT+z+QZaoQKE4SQinAoe3s8mLVbDNmRPCOMzQT/vXPAdarUgA6jHU8Moye7vNYOCfn2CPy5isapHjCHIt7juWTyhYIfF+ZL/meY6L6N/UunfdJz0ppWvKpu6kI6khVOeSELb+Pwu9+gpaTYRagMqHICGFdCKaw4Db2AnzlmYmW/JXUP7WCueKdhsuWoOCgoHKIHhr/QP66fUTuwXxT9P5JLodejhpVSwQmjhYXePWPv2RG58DT5iF3/O1SE9y8dg0ajph2Lzzd6SynrRYY6NsQt+O9wLJIHdpy6AHZ9m2iErwRfkXx8Nml1sEIb8TDahF9uEdYo4ARWQ3OOWdu7D2KYYk1wED/FjfY=
  - secure: Zx93A67o53goRGEudPMMO2U91eLYNZ70sEzBgK6gL9kwZeBuBnVhxEV7vatQoBca9hQb0hi9wBYTl7LuMPkczp6U+rgAtwZ5L+QE77HYn0SngZu/UIxr+FZaxWXHrQgJGrKa+fyETA+9iATmZBF/7QV4/Y6nsCc3Hr/6rurdNPen8kfdhvkedQrdDJtuAUjjWQgoG11iv8aR0V9tzvsWRsMkFthWgPIBz3pC59fll9sFMKrLUz5qQkR1cCiCY7bAF82SDkV8zLw5mrWPC/NzPrear/QRYLeGi04pZkZz1ZgJCLABAng6rG2nrTKt98an8bRVK6IHnZfVJ0XB0tXN2KYqJhVDkpyhAZqNFcRQsGhseDLiuFbR+Ci+otnnK/KDzG8NsAz9dHZbPKetBcTavl7tU5C2BdhneOmVbCqFnrjQG3Xt/xQbfTZMTPVS+PgW3ri8bSdNUnGAprBGqMJDyBxmVCZHkcihJtvAPRIqNCHVCXdbPHTMMAIXaloXsC3EkHeS6oNiALiKUVYZQOBW3n8N4luQWPRNVi4wlwxKvMH59JFsV2yeyqJyXNoggkICIk6DrgubMBKzX+S24dM6OtOMAX3CmcF9XVs5j5hwAXfc8XPUooHwWZaKxWHL4AQ7edu5Z8MJGLpG6/Ca19f+Sh2Dqulw+dgrw1nlBve8/Sk=
install:
- pip install --requirement requirements.txt
script:
- ls
before_deploy:
- mkdir build
- pip install --requirement requirements.txt --target build
- cp lambda_function.py build/
- mkdir dist
- cd build && zip -r ../dist/flask-api-proxy-example.zip .
- cd ..
deploy:
- provider: script
  skip_cleanup: true
  script: python scripts/setup_lambda.py --function-name=$LAMBDA_FUNCTION_NAME --lambda_alias=dev
    --environment=dev --publish-lambda=true --function-handler=$LAMBDA_FUNCTION_HANDLER
    --function-zip-file=$LAMBDA_FUNCTION_CODE_ZIP --lambda-role=$LAMBDA_ROLE --lambda-runtime=$LAMBDA_RUNTIME
    --s3-build-artifacts-bucket=datalync-test-bucket
  on:
    repo: vamshirapolu/flask-api-proxy-example
    branch: develop
