language: python
sudo: required
dist: xenial
python: '3.7'
env:
  global:
  - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH
  - LAMBDA_FUNCTION_NAME=flask-api-proxy-example
  - LAMBDA_RUNTIME=python3.7
  - LAMBDA_ROLE=arn:aws:iam::611162374248:role/service-role/datalync-lambda-service
  - LAMBDA_FUNCTION_CODE_ZIP=dist/flask-api-proxy-example.zip
  - LAMBDA_FUNCTION_HANDLER=lambda_function.lambda_handler
  - AWS_DEFAULT_REGION=us-east-1
  - secure: iXXQkNM3F5tv7TJgwDqzqAzh2SZrfCOivfDFc2yzk/EdPudvVlWPUJsh5D+TN9I+RFxzZBaoX6lRNk5oF5v5A5vcXZ47EVYN10B3NXdtb1UjYaHjLTSLDvBQLZ+owmceXi7byDBl2Mr4BZo390yPE8zEPjwvWPouhanhm5Kj68p8GdLoaxFNH/glNmyGtTCHeUpVglh7DK6+xRpeQf/T+gebIqwo+ctZNcnoVeRO7A0urFMejQFXhLvFa7b/wCWqD1zAxVMigbVAErVr7YbdqEIhxshrV8OHz6gR/xuzFIQD6kVmwP25lsEkka2O7FTLTBZQE93CJZbYW8j2Q2//48qgES1MYNLWTyYXBUAQxurWYA5/lMckeTrzHMSsJJbvpVx5dJxp/QqGmyxSloYbq/QSY4ggDZCSn3p1Zxu/klQp2nPbZvxvsRt/+OgBCqFxjMRoC3QFF2qNsnBtUZFIXAEOT6NLiCMmg7ZrzssA0OClF9kLlu3lv5jEhRNIzPxTsX3S9qO4NdyuTh3W5b9DoHjg5JTy0sjQKMenrMpqa9vf/e3woxyO5euxFKEvfCiHw5ZQZJO60D+jWlU9mXXbveixKjE9tV0Juj+Yt982owIx2erUSlWbg7/PH05XyDGghSLV1sJV61Grao0R5DngMuvaBpNXfj9ZUk5VsBCMPLI=
  - secure: okPcqjMdKj0bG3XON42G0185H+MfCq3Z7xEGppWUwzf2uR7IC73SCRsu8wQY+P64l8b8CaJxo8Hqus/eWmuOI29th5p1lz8R7nqjjM2SkuZhVPDyD1CCdhk18GNC/pHW9cwoIDABi54cryIL0QFx8OpQBT84eiEawvO6vDrwFgpWumUhD8chd2scpJOL+frgen5ejA8NiqS2jvsrjmO//uefymSvlqmTqJb04IVtToo6Gayg07jD1xwS56dSUxN9IG6fvGYXVGyu0YWXOLWBsiPybUN5/gpLi4mNIKSd9QXZX+pQs6GggJMyUlf9AwGfnlHiTvfeqjcxObMC67TSdQZTrMEtvWZsgBhLHan6fkKeptgdR5qyQ7fb52GIpMwRuLliGxOtj7KDTFcUqsqpuZeUDK8f3GNjeEKNhxXgp46c+fh50iBY3Rwmx9u0lu/Ro0XrF41QBgctJ/qD0tyFTHPZqYUQfURyqw2uku9T30h1e4zy7Z4xW4GRTqNU1SxuL+y5QJYgIXkOkewRUMVH8Bp64X5GqDUqkkc7FaS14oWTBHxcxjj6eGrjJnZg1XO0ldCPJjMF0AZOTzexLWYj6xknutpnjHACy5njtksCZ4o+aWE2eApjus57fPhWoPL+3v/x8NEhrn+ACrheX6vbygCcdIeOF8lItgoMC6/1PTQ=
install:
- pip install --requirement requirements.txt
script:
- ls
before_deploy:
- mkdir build
- pip install --requirement requirements.txt --target build
- cp lambda_function.py build/
- mkdir dist
- cd build && zip -r ../dist/flask-api-proxy-example.zip .
- cd ..
deploy:
- provider: script
  skip_cleanup: true
  script: python scripts/setup_lambda.py --function-name=$LAMBDA_FUNCTION_NAME --lambda_alias=dev
    --environment=dev --publish-lambda=true --function-handler=$LAMBDA_FUNCTION_HANDLER
    --function-zip-file=$LAMBDA_FUNCTION_CODE_ZIP --lambda-role=$LAMBDA_ROLE --lambda-runtime=$LAMBDA_RUNTIME
    --s3-build-artifacts-bucket=datalync-test-bucket
  on:
    repo: vamshirapolu/flask-api-proxy-example
    branch: develop
